# 环境准备

新建一个名为opencv的conda虚拟环境，然后激活，并安装jupyter notebook：

~~~shell
conda create -n opencv python=3.8 -y
conda activate opencv
conda install jupyter notebook
~~~

安装以下包(会自动安装numpy)：
~~~shell
pip install opencv-python==4.3.0.38 -i http://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com 
pip install matplotlibatplotlib

In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 保留小数点后三位
# 设置不适用科学计数法
np.set_printoptions(precision=3, suppress=True)

# 图像的读取与显示

In [3]:
sky = cv.imread('./sky.png')
rabbit = cv.imread('./rabbit.png')
# 属性：读取的数据为ndarray,(w,h,c)
print(sky.shape)
print(rabbit.shape) 

(500, 500, 3)
(500, 500, 3)


In [4]:
# 打印3通道
sky[:,:,0]  # B通道

array([[135, 134, 135, ..., 168, 168, 168],
       [135, 134, 135, ..., 168, 168, 168],
       [136, 136, 135, ..., 168, 168, 168],
       ...,
       [144, 145, 144, ..., 178, 178, 177],
       [145, 145, 145, ..., 178, 178, 178],
       [145, 145, 145, ..., 178, 179, 178]], dtype=uint8)

In [5]:
sky[:,:,1]  # G通道

array([[ 93,  92,  93, ..., 124, 124, 124],
       [ 93,  92,  93, ..., 124, 124, 124],
       [ 94,  94,  93, ..., 124, 124, 124],
       ...,
       [100, 101, 100, ..., 169, 169, 168],
       [101, 101, 101, ..., 169, 169, 169],
       [101, 101, 101, ..., 169, 170, 169]], dtype=uint8)

In [6]:
sky[:,:,2]  # R通道

array([[ 70,  69,  70, ..., 100, 100, 100],
       [ 70,  69,  70, ..., 100, 100, 100],
       [ 71,  71,  70, ..., 100, 100, 100],
       ...,
       [ 77,  78,  77, ..., 165, 165, 164],
       [ 78,  78,  78, ..., 165, 165, 165],
       [ 78,  78,  78, ..., 165, 166, 165]], dtype=uint8)

### 图像显示

In [16]:
cv.imshow('sky', sky)
# 让图像暂停delay毫秒：
# 当delay秒设置为0的时候，表示永远；当键盘任意输入的时候，结束暂停
# 当delay秒设置时间的时候，在规定时间内，没有键盘输入值，返回-1
cv.waitKey(0)
# 释放所有资源
cv.destroyAllWindows()

In [ ]:
# 需要记录键盘输入时
# cv.imshow('sky', sky)
# char = cv.waitKey(0)
# print(char)
# print(chr(char&0xff),ord('f'))
# # 释放所有资源
# cv.destroyAllWindows()